language: php
php:
  - 5.6


before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

  - composer require --dev satooshi/php-coveralls:dev-master
  - mkdir -p build/logs

  - phpenv rehash

script:
  - vendor/bin/phpcs -p --standard=PSR2 ./src ./tests

  - phpunit

  - vendor/bin/coveralls -v
